### ISSUE TITLE
Velocity controlled CheesyDrive testing and optimization

### ISSUE THREAD

**Issue by jdlanning** [frc1675/frc1675-2022#30]
We will need to spend some time testing the Cheesy Drive PID for velocity control to ensure it is functioning properly after recent changes in the Drive subsystem.

One thing to keep in mind are the units for the velocity measurement (we may want to think of it in ft/sec but the motor controller thinks in terms of rotations/sec). So there could be some conversion required similar to what we did for position control

**Comment by python-42** [comment]
It didnt work
